### ISSUE TITLE
Discrepancy in creating new ESPD request

### ISSUE THREAD

**Issue by botrot** [ESPD/espd#224] opened 2019-08-14 12:17 UTC
When creating a new ESPD request as a contracting entity and navigate to the "Exclusion" page, sections A and B have different options which are check boxes and here it comes the difference when creating request as a contracting authority those A and B sections all the check boxes are hidden and cant be optional. I hope there has be an explanation for that but it might be a bug too ?

**Comment by ec-mcs** [comment] 2019-08-14 13:29
Actually this is not a bug but a feature. While contracting authorities MUST use A and B of the exclusion grounds (therefore greyed out), these are optional for contracting entities (usable). And that is the reason why we distinguish as an entry point for the ESPD if they are an entity or authority. 
I close this issue.

**Closed as completed by ec-mcs** 2019-08-14 13:29 UTC
